# Generated by Django 3.0.8 on 2020-07-12 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20200711_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('facutly', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('fee', models.FloatField()),
                ('duration', models.CharField(max_length=50)),
            ],
        ),
    ]
